
#############################
# log_viewer_node.py
#############################
import os

class AiTKLogViewerNode:
    """
    A node to view training logs generated by AiTKTrainerNode.
    It reads the last N lines of the log file and outputs as STRING.

    Useful for real-time polling by the user.
    """
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "log_path": ("STRING", {"default": "/root/ai-toolkit/output/latest/log.txt"}),
                "num_lines": ("INT", {"default": 20, "min": 1, "max": 2000}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("log_text",)
    FUNCTION = "run"
    CATEGORY = "AiToolKit/Utils"

    def run(self, log_path, num_lines):
        if not os.path.exists(log_path):
            return (f"[LogViewer] Log file not found: {log_path}",)

        try:
            with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()
            tail = "".join(lines[-num_lines:])
            return (tail if tail else "[LogViewer] Log is empty.",)
        except Exception as e:
            return (f"[LogViewer] Error reading log: {e}",)
